version: '3.8'

services:
  backend:
    build: ./backend
    container_name: fastapi-backend
    ports:
      - "8000:8000"
    restart: always

  frontend:
    build: ./frontend
    container_name: streamlit-frontend
    ports:
      - "8501:8501"
    depends_on:
      - backend
    restart: always
