name: CI/CD Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Set up QEMU (for multi-arch builds)
      uses: docker/setup-qemu-action@v3

    - name: Build Backend Image
      run: docker build -t my-backend ./backend

    - name: Build Frontend Image
      run: docker build -t my-frontend ./frontend

    - name: Run docker-compose for integration
      run: |
        docker compose up -d
        sleep 10

    - name: Show Running Containers
      run: docker ps -a

    - name: Wait for Streamlit to be healthy
      run: |
        timeout=60
        while [ $timeout -gt 0 ]; do
          health=$(docker inspect --format='{{.State.Health.Status}}' streamlit-frontend || echo "starting")
          echo "Streamlit Health: $health"
          if [ "$health" = "healthy" ]; then
            break
          fi
          sleep 5
          timeout=$((timeout - 5))
        done

        if [ "$health" != "healthy" ]; then
          echo "Streamlit is not healthy"
          docker logs streamlit-frontend
          exit 1
        fi

    - name: Test FastAPI Health
      run: |
        curl --retry 5 --retry-delay 5 --fail http://localhost:8000/docs || exit 1

    - name: Test Streamlit UI
      run: |
        curl --retry 5 --retry-delay 5 --fail http://localhost:8501 || exit 1
