name: CI/CD Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Set up Docker
      uses: docker/setup-qemu-action@v3

    # OPTIONAL: Log in to DockerHub if pushing images
    # - name: Log in to DockerHub
    #   uses: docker/login-action@v3
    #   with:
    #     username: ${{ secrets.DOCKER_USERNAME }}
    #     password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build Backend Image
      run: docker build -t my-backend ./backend

    - name: Build Frontend Image
      run: docker build -t my-frontend ./frontend

    - name: Run docker compose for integration
      run: |
        docker compose up -d
        sleep 15  # wait for services to start

    - name: Test FastAPI Health
      run: |
        curl --fail http://localhost:8000/docs || exit 1

    - name: Test Streamlit UI
      run: |
        curl --fail http://localhost:8501 || exit 1
