name: CI/CD Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Set up Docker Compose
      run: |
        sudo apt-get update
        sudo apt-get install -y docker-compose

    - name: Build Backend Image
      run: docker build -t my-backend ./backend

    - name: Build Frontend Image
      run: docker build -t my-frontend ./frontend

    - name: Run docker-compose for integration
      run: |
        docker-compose up -d
        echo "Waiting for services to become healthy..."
        sleep 30

    - name: Check running containers
      run: docker ps

    - name: Test FastAPI Health
      run: |
        curl --retry 5 --retry-delay 5 --fail http://localhost:8000/docs

    - name: Test Streamlit UI
      run: |
        curl --retry 5 --retry-delay 5 --fail http://localhost:8501
